// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ywddlchfrtibshljqlvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3ZGRsY2hmcnRpYnNobGpxbHZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NzU5OTcsImV4cCI6MjA2MjE1MTk5N30.2biJs-6lilIpOHJVcmMDzm7GaaxYDy6uRXMsefhLkhA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);